name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-function-app:
    
    env:
      AZURE_FUNCTIONAPP_NAME: 'fa-innovate-23'
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './Backend'
      DOTNET_VERSION: '6.0.x'  
    
    runs-on: windows-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.FUNCTION_APP_PUBLISH_PROFILEgithub actions  }}
